doc:
	man2html man/hudx2country.1 | grep -v 'Content-type:' > html/hudx2country.html
	man2html man/hudxreport.1 | grep -v 'Content-type:' > html/hudxreport.html
	man2html man/hudxreport-filter.1 | grep -v 'Content-type:' > html/hudxreport-filter.html
	man2html man/hudxhumans.1 | grep -v 'Content-type:' > html/hudxhumans.html
	man2html man/hudxsession.1 | grep -v 'Content-type:' > html/hudxsession.html
clean:
	rm -f html/*
